# Site settings
name: JaneDoesSecurity
description: Cybersecurity Professional | CISSP
url: https://janedoessecurity.com
avatar: https://github.com/janedoessecurity.png

# Post settings
excerpt_separator: <!--more-->
permalink: /:title/

# Footer links
footer-links:
  github: janedoessecurity
  linkedin: jane-thompson-iom-infosec
