# Name of your site (displayed in the header)
name: JaneDoesSecurity

# Short bio or description (displayed in the header)
description: Cybersecurity Professional | CISSP

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://github.com/janedoessecurity.png

# Your website URL
url: https://janedoessecurity.com

# Footer links - add your social media
footer-links:
  dribbble:
  email: jane@janedoessecurity.com  # if you set up email
  facebook:
  flickr:
  github: janedoessecurity
  instagram:
  linkedin:  # add your LinkedIn username if you want
  pinterest:
  rss: rss
  twitter:  # add if you have Twitter
  stackoverflow: 
  youtube: 
  googleplus:
